/**
 * The static reference: coverage and incidence-cosine over the sphere, computed
 * ONCE and never refreshed by a bench round.
 *
 *     node packages/bench/src/reference.ts            # write progress/reference/coverage-reference.json
 *     node packages/bench/src/reference.ts --check    # recompute and DIFF against the stored file
 *
 * ## Why this is a separate command
 *
 * This is a correctness check wearing a visual's clothes. PARAMETERS.md §4.2 says
 * overlap multiplicity never exceeds 2 — correcting a rev 1 error that claimed
 * 3- and 4-way overlap toward the poles — and §4.3 says the permanently unlit
 * polar region is a four-lobed scalloped shape rather than a circular cap. Both
 * claims are counterintuitive, both are easy to break, and a broken build
 * produces a picture that still looks like a sphere.
 *
 * If this file were regenerated by every bench round it would always agree with
 * whatever the forward model currently believes, and the check would be
 * vacuous — the reference would silently follow the bug. So the round refreshes
 * the progress page and never touches this file, `--check` is the only thing
 * that compares a fresh computation against the stored one, and regenerating it
 * is a deliberate act by a human who has read what changed.
 *
 * ## What is stored
 *
 * The FIELDS, not a picture. `progress.ts` draws the maps as SVG from these
 * arrays, and `analyseCoverageReference` derives the pass/fail claims from the
 * same arrays — so the page asserts its properties from the data it plots
 * rather than from a caption somebody typed.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

import { PARAMETER_TABLE } from '../../calibration/src/parameters.ts';
import { nominalRig, nominalBlend } from '../../sim/src/scene.ts';
import { prepareRig } from '../../sim/src/optics.ts';
import {
  bestIncidenceCosine,
  coverageBoundaryLatitude,
  overlapMultiplicity,
  polarMask,
  unlitPolarAreaFraction,
  usableLatitude,
} from '../../sim/src/coverage.ts';

export const REFERENCE_SCHEMA = 'sphere-sim/coverage-reference@1';

/** Where the stored reference lives, relative to the repository root. */
export const REFERENCE_RELATIVE_PATH = 'progress/reference/coverage-reference.json';

export interface ReferenceGrid {
  width: number;
  height: number;
  /** Cell centres: `lat = 90 - (y + 0.5) / height * 180`, matching `registration.ts`. */
  latFromTopDeg: true;
}

export interface CoverageReference {
  schema: typeof REFERENCE_SCHEMA;
  /** Stamped so a reader can see how old the reference is relative to the page. */
  generatedAt: string;
  gitCommit: string;
  rig: {
    projectorCount: number;
    azimuthsDeg: number[];
    distanceM: number;
    radiusM: number;
    centerHeightM: number;
    projectorHeightM: number;
    resX: number;
    resY: number;
    maskLoDeg: number;
    maskHiDeg: number;
    bottomOnly: boolean;
  };
  grid: ReferenceGrid;
  /** How many projectors light each cell. Values are small integers. */
  multiplicity: number[];
  /** Best `cos(incidence)` over the projectors that light the cell; -1 = unlit. */
  incidenceCos: number[];
  /** Polar mask attenuation per latitude row, 1 = visible, 0 = fully masked. */
  maskByRow: number[];
  /** The unlit-region boundary, by longitude, from the general limb test. */
  boundary: {
    lonDeg: number[];
    northLatDeg: number[];
    southLatDeg: number[];
  };
  /** Latitude where `cos(incidence)` falls to 0.2 — §4.3's streak limit. */
  usable: {
    lonDeg: number[];
    northLatDeg: number[];
  };
  /** Closed forms §4.3 states, for comparison with the computed boundary. */
  analytic: {
    /** `acos(R/d)`: the limb along a projector's own meridian. §4.3 says 80.4. */
    meridianLimitDeg: number;
    /** `cos(lat)*cos(45) = R/d`: the limb in a seam direction. §4.3 says 76.3. */
    seamLimitDeg: number;
    /** `(1 - sin lat)/2`, the circular caps those two latitudes cut. */
    capAboveMeridianLimit: number;
    capAboveSeamLimit: number;
    /** Integrated over the true boundary. docs/AMENDMENTS.md A-05. */
    unlitFractionNorth: number;
    unlitFractionSouth: number;
    /** §4.3's stated per-pole range, quoted so the disagreement stays visible. */
    specStatedRange: [number, number];
  };
}

// ---------------------------------------------------------------------------
// Computing it
// ---------------------------------------------------------------------------

export interface ReferenceOptions {
  width?: number;
  height?: number;
  /** Longitude samples for the boundary curve. */
  boundarySamples?: number;
  distanceM?: number;
  projectorCount?: number;
  generatedAt?: string;
  gitCommit?: string;
}

const DEG2RAD = Math.PI / 180;

export function buildCoverageReference(options: ReferenceOptions = {}): CoverageReference {
  const width = options.width ?? 360;
  const height = options.height ?? 180;
  const boundarySamples = options.boundarySamples ?? 360;
  const distanceM = options.distanceM ?? PARAMETER_TABLE.d_proj.nominal;
  const projectorCount = options.projectorCount ?? 4;

  const radiusM = PARAMETER_TABLE.R.nominal;
  const centerHeightM = PARAMETER_TABLE.h_center.nominal;
  const projectorHeightM = PARAMETER_TABLE.h_proj.nominal;
  const resX = 1920;
  const resY = 1080;

  const cal = nominalRig({
    projectorCount,
    distanceM,
    radiusM,
    centerHeightM,
    projectorHeightM,
    resX,
    resY,
  });
  const rig = prepareRig(cal);
  const blend = nominalBlend();

  const multiplicity: number[] = new Array<number>(width * height).fill(0);
  const incidenceCos: number[] = new Array<number>(width * height).fill(-1);
  const maskByRow: number[] = new Array<number>(height).fill(1);

  for (let y = 0; y < height; y++) {
    const latDeg = 90 - ((y + 0.5) / height) * 180;
    maskByRow[y] = round(polarMask(latDeg, blend, 'latitude'), 4);
    for (let x = 0; x < width; x++) {
      const lonDeg = -180 + ((x + 0.5) / width) * 360;
      const idx = y * width + x;
      const n = overlapMultiplicity(latDeg, lonDeg, rig);
      multiplicity[idx] = n;
      incidenceCos[idx] = n === 0 ? -1 : round(bestIncidenceCosine(latDeg, lonDeg, rig), 4);
    }
  }

  const lonDeg: number[] = [];
  const northLatDeg: number[] = [];
  const southLatDeg: number[] = [];
  for (let i = 0; i < boundarySamples; i++) {
    const lon = -180 + (360 * i) / boundarySamples;
    lonDeg.push(round(lon, 6));
    northLatDeg.push(round(coverageBoundaryLatitude(lon, rig, 1), 6));
    southLatDeg.push(round(coverageBoundaryLatitude(lon, rig, -1), 6));
  }

  const usableLon: number[] = [];
  const usableLat: number[] = [];
  for (let i = 0; i < 72; i++) {
    const lon = -180 + (360 * i) / 72;
    usableLon.push(round(lon, 6));
    usableLat.push(round(usableLatitude(lon, rig, 0.2, 1), 6));
  }

  const meridianLimitDeg = (Math.acos(radiusM / distanceM) * 180) / Math.PI;
  const seamLimitDeg =
    (Math.acos(radiusM / distanceM / Math.cos(45 * DEG2RAD)) * 180) / Math.PI;

  return {
    schema: REFERENCE_SCHEMA,
    generatedAt: options.generatedAt ?? new Date().toISOString(),
    gitCommit: options.gitCommit ?? gitCommit(),
    rig: {
      projectorCount,
      azimuthsDeg: cal.projectors.map((p) =>
        round((Math.atan2(p.pose.position.y, p.pose.position.x) * 180) / Math.PI, 6),
      ),
      distanceM,
      radiusM,
      centerHeightM,
      projectorHeightM,
      resX,
      resY,
      maskLoDeg: blend.maskLoDeg,
      maskHiDeg: blend.maskHiDeg,
      bottomOnly: blend.bottomOnly,
    },
    grid: { width, height, latFromTopDeg: true },
    multiplicity,
    incidenceCos,
    maskByRow,
    boundary: { lonDeg, northLatDeg, southLatDeg },
    usable: { lonDeg: usableLon, northLatDeg: usableLat },
    analytic: {
      meridianLimitDeg: round(meridianLimitDeg, 6),
      seamLimitDeg: round(seamLimitDeg, 6),
      capAboveMeridianLimit: round((1 - Math.sin(meridianLimitDeg * DEG2RAD)) / 2, 8),
      capAboveSeamLimit: round((1 - Math.sin(seamLimitDeg * DEG2RAD)) / 2, 8),
      unlitFractionNorth: round(unlitPolarAreaFraction(rig, 720, 1), 8),
      unlitFractionSouth: round(unlitPolarAreaFraction(rig, 720, -1), 8),
      specStatedRange: [0.014, 0.028],
    },
  };
}

function round(v: number, decimals: number): number {
  if (!Number.isFinite(v)) return v;
  const f = Math.pow(10, decimals);
  const r = Math.round(v * f) / f;
  return r === 0 ? 0 : r;
}

function gitCommit(): string {
  try {
    return execFileSync('git', ['rev-parse', 'HEAD'], {
      cwd: repoRoot(),
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch {
    return 'unknown';
  }
}

function repoRoot(): string {
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
}

// ---------------------------------------------------------------------------
// The checks — derived from the arrays, not from a caption
// ---------------------------------------------------------------------------

export interface ReferenceCheck {
  id: string;
  claim: string;
  /** What the data says, in words, with the number in it. */
  observed: string;
  pass: boolean;
  /** What a failure would mean. Printed whether or not it failed. */
  failureMeans: string;
}

export interface ReferenceChecks {
  maxMultiplicity: number;
  /** Area fraction of the sphere at each multiplicity, cos(lat)-weighted. */
  areaByMultiplicity: number[];
  /** Local minima of the northern boundary latitude around the full 360. */
  lobeCount: number;
  lobeLongitudesDeg: number[];
  boundaryMinDeg: number;
  boundaryMaxDeg: number;
  /** Max minus min. Zero would mean a circular cap. */
  scallopDepthDeg: number;
  unlitFractionNorth: number;
  capAboveMeridianLimit: number;
  capAboveSeamLimit: number;
  checks: ReferenceCheck[];
  pass: boolean;
}

/**
 * Count the lobes of a periodic curve.
 *
 * Hysteresis rather than a raw neighbour comparison: the boundary comes from a
 * 60-iteration bisection, so it carries numerical wobble far below the 4 degrees
 * of scalloping the shape actually has, and a naive local-minimum test would
 * count that wobble. A direction switch only registers once the curve has moved
 * `tolDeg` against its current direction.
 */
export function countLobes(values: readonly number[], tolDeg = 0.05): number[] {
  const n = values.length;
  if (n < 4) return [];
  let start = 0;
  let minValue = values[0];
  for (let i = 1; i < n; i++) {
    if (values[i] < minValue) {
      minValue = values[i];
      start = i;
    }
  }
  const at = (i: number): number => values[(i + start + n) % n];

  const minima: number[] = [];
  let direction: 1 | -1 = 1;
  let extreme = at(0);
  let extremeIndex = 0;
  for (let k = 1; k <= n; k++) {
    const v = at(k % n);
    if (direction === 1) {
      if (v > extreme) {
        extreme = v;
        extremeIndex = k;
      } else if (extreme - v > tolDeg) {
        direction = -1;
        extreme = v;
        extremeIndex = k;
      }
    } else {
      if (v < extreme) {
        extreme = v;
        extremeIndex = k;
      } else if (v - extreme > tolDeg) {
        direction = 1;
        minima.push((extremeIndex + start) % n);
        extreme = v;
        extremeIndex = k;
      }
    }
  }
  // The scan starts at the global minimum, so the curve opens ascending and the
  // final descent's minimum is that same starting point, already counted.
  if (direction === -1) minima.push((extremeIndex + start) % n);
  return [...new Set(minima)].sort((a, b) => a - b);
}

export function analyseCoverageReference(ref: CoverageReference): ReferenceChecks {
  const { width, height } = ref.grid;

  let maxMultiplicity = 0;
  const areaByMultiplicity: number[] = [];
  let totalWeight = 0;
  for (let y = 0; y < height; y++) {
    const latDeg = 90 - ((y + 0.5) / height) * 180;
    const w = Math.cos(latDeg * DEG2RAD);
    for (let x = 0; x < width; x++) {
      const n = ref.multiplicity[y * width + x];
      if (n > maxMultiplicity) maxMultiplicity = n;
      areaByMultiplicity[n] = (areaByMultiplicity[n] ?? 0) + w;
      totalWeight += w;
    }
  }
  for (let i = 0; i < areaByMultiplicity.length; i++) {
    areaByMultiplicity[i] = (areaByMultiplicity[i] ?? 0) / totalWeight;
  }

  const north = ref.boundary.northLatDeg;
  const lobeIdx = countLobes(north);
  const lobeLongitudesDeg = lobeIdx.map((i) => ref.boundary.lonDeg[i]);
  let boundaryMinDeg = Infinity;
  let boundaryMaxDeg = -Infinity;
  for (const v of north) {
    if (v < boundaryMinDeg) boundaryMinDeg = v;
    if (v > boundaryMaxDeg) boundaryMaxDeg = v;
  }
  const scallopDepthDeg = boundaryMaxDeg - boundaryMinDeg;

  // The extremum of a sampled curve can only be located to the sample spacing,
  // and the boundary is locally quadratic at both a meridian and a seam, so the
  // depth error is proportional to (step/2)^2. The coefficient is measured: a
  // 2-degree grid whose samples straddle a seam by 1 degree misses the seam
  // minimum by 0.236 degrees. Stated as a tolerance rather than pinned to the
  // default grid, so the same check stays honest at any density — at the
  // default 1-degree step it is 0.125 degrees, and a real limb error is degrees.
  const lonStepDeg = ref.boundary.lonDeg.length > 0 ? 360 / ref.boundary.lonDeg.length : 1;
  const boundaryTolDeg = 0.05 + 0.3 * (lonStepDeg / 2) * (lonStepDeg / 2);

  const unlit = ref.analytic.unlitFractionNorth;
  const capMeridian = ref.analytic.capAboveMeridianLimit;
  const capSeam = ref.analytic.capAboveSeamLimit;

  const checks: ReferenceCheck[] = [
    {
      id: 'multiplicity',
      claim: 'PARAMETERS.md §4.2 — overlap multiplicity is 1 or 2 everywhere, never 3 or 4.',
      observed: `max multiplicity over ${width * height} cells is ${maxMultiplicity}; area split ${areaByMultiplicity
        .map((f, i) => `${i}-way ${(100 * f).toFixed(1)}%`)
        .join(', ')}`,
      pass: maxMultiplicity <= 2,
      failureMeans:
        'A 3- or 4-way overlap means the limb test, the raster bound or the projector placement is wrong. Rev 1 of the spec asserted 3- and 4-way overlap toward the poles and §4.2 exists to correct it, so this is the exact error the reference guards.',
    },
    {
      id: 'four-lobed',
      claim:
        'PARAMETERS.md §4.3 — the unlit polar region is four-lobed and scalloped, not a circular cap.',
      observed: `${lobeIdx.length} local minima at longitudes ${lobeLongitudesDeg
        .map((l) => `${l.toFixed(0)}°`)
        .join(', ')}; boundary latitude runs ${boundaryMinDeg.toFixed(2)}° to ${boundaryMaxDeg.toFixed(2)}° (${scallopDepthDeg.toFixed(2)}° of scallop)`,
      pass: lobeIdx.length === 4 && scallopDepthDeg > 1,
      failureMeans:
        'A circular polar cap (zero scallop depth) means coverage is being tested with a rotationally symmetric approximation rather than against each lens. Anything other than four minima means the projectors are not at the four nominal azimuths.',
    },
    {
      id: 'lobes-at-seams',
      claim: 'The lobes sit in the seam directions, 45° from each projector meridian.',
      observed: `minima at ${lobeLongitudesDeg.map((l) => `${l.toFixed(0)}°`).join(', ')} against projector meridians at ${ref.rig.azimuthsDeg.map((a) => `${a.toFixed(0)}°`).join(', ')}`,
      pass: lobeLongitudesDeg.every((l) =>
        ref.rig.azimuthsDeg.some((a) => angularGap(l, a + 45) < 5 || angularGap(l, a - 45) < 5),
      ),
      failureMeans:
        'A minimum on a projector meridian rather than between two would invert the geometry: coverage would reach highest where two lenses agree least.',
    },
    {
      id: 'boundary-matches-closed-form',
      claim: `The computed boundary reproduces §4.3's own latitudes: ${ref.analytic.meridianLimitDeg.toFixed(2)}° on a meridian, ${ref.analytic.seamLimitDeg.toFixed(2)}° in a seam.`,
      observed: `computed max ${boundaryMaxDeg.toFixed(3)}° (closed form ${ref.analytic.meridianLimitDeg.toFixed(3)}°), computed min ${boundaryMinDeg.toFixed(3)}° (closed form ${ref.analytic.seamLimitDeg.toFixed(3)}°), tolerance ${boundaryTolDeg.toFixed(3)}° at a ${lonStepDeg.toFixed(2)}° longitude step`,
      pass:
        Math.abs(boundaryMaxDeg - ref.analytic.meridianLimitDeg) < boundaryTolDeg &&
        Math.abs(boundaryMinDeg - ref.analytic.seamLimitDeg) < boundaryTolDeg,
      failureMeans:
        'The bisection walks the general vector limb test and the closed form comes from §4.1. They agreeing is what says the general renderer and the spec arithmetic describe the same rig.',
    },
    {
      id: 'unlit-area-between-caps',
      claim:
        'The unlit area lies strictly between the two circular caps its own boundary latitudes cut — the mathematical content of "scalloped, not circular".',
      observed: `${(100 * unlit).toFixed(3)}% per pole, bounded by ${(100 * capMeridian).toFixed(3)}% (cap at the meridian limit) and ${(100 * capSeam).toFixed(3)}% (cap at the seam limit). §4.3 states 1.4–2.8%; docs/AMENDMENTS.md A-05 explains the disagreement.`,
      pass: unlit > capMeridian && unlit < capSeam,
      failureMeans:
        'Outside those bounds the area integral and the boundary curve disagree, so one of them is wrong. Note this check deliberately does NOT test §4.3\'s stated 1.4–2.8% range: A-05 shows that range is unreachable from §4.3\'s own latitudes.',
    },
  ];

  return {
    maxMultiplicity,
    areaByMultiplicity,
    lobeCount: lobeIdx.length,
    lobeLongitudesDeg,
    boundaryMinDeg,
    boundaryMaxDeg,
    scallopDepthDeg,
    unlitFractionNorth: unlit,
    capAboveMeridianLimit: capMeridian,
    capAboveSeamLimit: capSeam,
    checks,
    pass: checks.every((c) => c.pass),
  };
}

function angularGap(a: number, b: number): number {
  let d = Math.abs(((a - b) % 360) + 360) % 360;
  if (d > 180) d = 360 - d;
  return d;
}

// ---------------------------------------------------------------------------
// Reading and writing
// ---------------------------------------------------------------------------

export function loadCoverageReference(file: string): CoverageReference | null {
  if (!fs.existsSync(file)) return null;
  try {
    const parsed = JSON.parse(fs.readFileSync(file, 'utf8')) as CoverageReference;
    return parsed.schema === REFERENCE_SCHEMA ? parsed : null;
  } catch {
    return null;
  }
}

/** Serialise with the big numeric arrays inline, as `results.ts` does. */
export function stringifyReference(ref: CoverageReference): string {
  const compact = (a: readonly number[]): string => `[${a.join(',')}]`;
  const body = {
    ...ref,
    multiplicity: '@multiplicity',
    incidenceCos: '@incidenceCos',
    maskByRow: '@maskByRow',
  };
  let text = JSON.stringify(body, null, 2);
  text = text.replace('"@multiplicity"', compact(ref.multiplicity));
  text = text.replace('"@incidenceCos"', compact(ref.incidenceCos));
  text = text.replace('"@maskByRow"', compact(ref.maskByRow));
  return `${text}\n`;
}

/** The two fields that are allowed to differ between two computations. */
function withoutStamp(ref: CoverageReference): CoverageReference {
  return { ...ref, generatedAt: '', gitCommit: '' };
}

function main(): void {
  const argv = process.argv.slice(2);
  const check = argv.includes('--check');
  const root = repoRoot();
  const file = path.join(root, REFERENCE_RELATIVE_PATH);

  const fresh = buildCoverageReference();
  const analysis = analyseCoverageReference(fresh);

  if (check) {
    const stored = loadCoverageReference(file);
    if (stored === null) {
      process.stdout.write(`reference: no stored file at ${REFERENCE_RELATIVE_PATH}\n`);
      process.exitCode = 1;
      return;
    }
    const same =
      stringifyReference(withoutStamp(stored)) === stringifyReference(withoutStamp(fresh));
    for (const c of analysis.checks) {
      process.stdout.write(`  ${c.pass ? 'PASS' : 'FAIL'}  ${c.id}: ${c.observed}\n`);
    }
    process.stdout.write(
      same
        ? 'reference: stored file matches a fresh computation.\n'
        : 'reference: STORED FILE DIFFERS from a fresh computation. Read what changed before regenerating.\n',
    );
    process.exitCode = same && analysis.pass ? 0 : 1;
    return;
  }

  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, stringifyReference(fresh));
  for (const c of analysis.checks) {
    process.stdout.write(`  ${c.pass ? 'PASS' : 'FAIL'}  ${c.id}: ${c.observed}\n`);
  }
  process.stdout.write(
    `reference: written ${REFERENCE_RELATIVE_PATH} (${analysis.pass ? 'all checks pass' : 'CHECKS FAILED — do not commit this'})\n`,
  );
  process.exitCode = analysis.pass ? 0 : 1;
}

if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  main();
}
