// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The Zyra Project

/**
 * Taking the operator's existing files in, so the restore point can cover them.
 *
 * Phase 4 of `docs/OPERATOR-PATH.md` landed its accounting half first and said
 * plainly what that left:
 *
 * > **today the refusal always fires**, because the page is never given the
 * > files it would overwrite. That is the next piece of work and it is small —
 * > the page already has a picker for the config, and the same treatment for
 * > the current warp and alignment files turns the refusal into a green light.
 *
 * This is that piece. `planRestore` already covers any target it holds an
 * original for; nothing was ever handing it the warp and alignment originals,
 * because the page GENERATES those and had never seen what sits at their paths.
 * An operator has seen them. This lets them say so.
 *
 * ## Why matching by name is determined here rather than guessed
 *
 * `restore.ts` is emphatic that "a near-match is not a match: restoring a file
 * to a path it did not come from is how a config lands in the wrong projector's
 * directory". That rule is what makes this module's job narrow.
 *
 * A picked file arrives with a NAME, not a path — browsers give a bare
 * `File.name` from a multi-select. So something has to relate `P1.data` to the
 * target `warp/P1.data`. The reason that is not a guess is that the targets are
 * generated by this page from the rig, one per projector, and their basenames
 * are therefore distinct: `warp/<id>.data` and `alignment/<id>.alignment`
 * differ by extension, and two projectors cannot share an id.
 *
 * But distinct-by-construction is exactly the kind of claim this project has
 * been caught making without checking, so {@link adoptOriginals} CHECKS it: a
 * name matching two or more targets is refused and both paths are named, rather
 * than silently taking the first. If the invariant ever stops holding, the
 * operator is told instead of being handed a file in the wrong place.
 *
 * ## What it still cannot know, and says
 *
 * That the bytes handed in are the ones currently at that path on the sphere.
 * An operator can pick last month's backup, or a file from the other dome, and
 * nothing in a browser can tell. This module reports the mapping it made, file
 * by file, so the person who does know can read it — which is the only check
 * available and is therefore the one worth printing.
 */

import type { HeldOriginal, InstallTarget } from './restore.ts';
import { TARGET_KINDS } from './restore.ts';

/** One file as the picker handed it over. */
export interface PickedFile {
  /** `File.name` — a bare basename, with no directory on it. */
  name: string;
  bytes: Uint8Array;
}

/** One file's fate: the target it was taken as, or why it was not taken. */
export interface Adoption {
  name: string;
  /** The target path it will be restored to, or null when it was refused. */
  path: string | null;
  /** Why it was refused. Empty when it was taken. */
  problem: string;
}

export interface AdoptResult {
  /** Ready to hand to `planRestore` beside anything already held. */
  held: HeldOriginal[];
  /** Every picked file, in the order it was offered, taken or not. */
  adoptions: Adoption[];
  /** Targets that still have no original, so the operator knows what is left. */
  stillUncovered: InstallTarget[];
  /** One line stating where things stand. Always present. */
  summary: string;
}

/** The last path segment, which is what a browser gives as `File.name`. */
function basename(path: string): string {
  const cut = path.lastIndexOf('/');
  return cut < 0 ? path : path.slice(cut + 1);
}

/**
 * Take what the operator picked, and say what each file was taken as.
 *
 * `targets` is the full install list. `alreadyHeld` are paths whose originals
 * the page holds by another route — in practice the config, which arrives
 * through its own picker because the config is PATCHED and its bytes are needed
 * for more than the restore point. A file offered for a path already held is
 * refused rather than overwriting it: the config picker's bytes are the ones
 * actually being patched, and two different originals for one path is a
 * disagreement the page cannot settle.
 */
export function adoptOriginals(
  targets: readonly InstallTarget[],
  picked: readonly PickedFile[],
  alreadyHeld: readonly HeldOriginal[] = [],
): AdoptResult {
  const heldPaths = new Set(alreadyHeld.map((h) => h.path));

  // Names are collected rather than assumed unique. See the module note.
  const byName = new Map<string, InstallTarget[]>();
  for (const t of targets) {
    const list = byName.get(basename(t.path)) ?? [];
    list.push(t);
    byName.set(basename(t.path), list);
  }

  const held: HeldOriginal[] = [];
  const adoptions: Adoption[] = [];
  const taken = new Set<string>();

  for (const file of picked) {
    const hits = byName.get(file.name) ?? [];
    if (hits.length === 0) {
      adoptions.push({
        name: file.name,
        path: null,
        problem:
          `Nothing this archive installs is called ${file.name}, so it was not taken. The ` +
          `files that would be overwritten are listed below by the name this page writes them ` +
          `under.`,
      });
      continue;
    }
    if (hits.length > 1) {
      // Not reachable while ids are unique and the two kinds differ by
      // extension — which is why it is checked rather than asserted.
      adoptions.push({
        name: file.name,
        path: null,
        problem:
          `${file.name} could be ${hits.map((h) => h.path).join(' or ')}, and this page cannot ` +
          `tell which you meant. Neither was taken.`,
      });
      continue;
    }
    const target = hits[0];
    if (target === undefined) continue;
    if (heldPaths.has(target.path)) {
      adoptions.push({
        name: file.name,
        path: null,
        problem:
          `${target.path} already has an original — the one loaded through its own picker, ` +
          `which is the copy being patched. This file was not taken, so the two cannot ` +
          `disagree.`,
      });
      continue;
    }
    if (taken.has(target.path)) {
      adoptions.push({
        name: file.name,
        path: null,
        problem: `${target.path} was already given an original in this selection. Only the ` +
          `first was taken, so a second reading of the same path cannot silently replace it.`,
      });
      continue;
    }
    taken.add(target.path);
    held.push({ path: target.path, bytes: file.bytes });
    adoptions.push({ name: file.name, path: target.path, problem: '' });
  }

  const covered = new Set([...heldPaths, ...taken]);
  const stillUncovered = targets.filter((t) => !covered.has(t.path));

  return { held, adoptions, stillUncovered, summary: describe(targets, covered, stillUncovered) };
}

/** Where things stand, in the operator's words rather than in counts alone. */
function describe(
  targets: readonly InstallTarget[],
  covered: ReadonlySet<string>,
  stillUncovered: readonly InstallTarget[],
): string {
  if (targets.length === 0) return 'This archive writes no files, so there is nothing to cover.';
  if (stillUncovered.length === 0) {
    return (
      `All ${targets.length} files the archive installs now have an original travelling with ` +
      `it. Installing is reversible: the archive carries a copy of everything it overwrites.`
    );
  }
  const kinds = new Map<string, number>();
  for (const t of stillUncovered) kinds.set(t.kind, (kinds.get(t.kind) ?? 0) + 1);
  const missing = [...kinds.entries()]
    .map(([kind, n]) => {
      const words = TARGET_KINDS[kind as keyof typeof TARGET_KINDS];
      return `${n} ${n === 1 ? words.one : words.many}`;
    })
    .join(' and ');
  return (
    `${covered.size} of ${targets.length} files the archive installs have an original ` +
    `travelling with them. Still missing: ${missing}. Hand those in and the archive becomes a ` +
    `restore point.`
  );
}

/**
 * What to tell the operator to go and find, listed by the path it goes back to.
 *
 * Deliberately the TARGET path rather than the picked name, because that is the
 * thing they have to locate on their own machine and the only name this page
 * can be sure of.
 */
export function wanted(stillUncovered: readonly InstallTarget[]): string[] {
  return stillUncovered.map((t) => t.path);
}
