/**
 * The PARAMETERS.md table, transcribed as data.
 *
 * Every entry carries its provenance class and, where a sweep needs one, a
 * plausible range. `rangeSource` records whether PARAMETERS.md states that range
 * or whether we inferred it — an inferred range on an ASSUME constant is an
 * assumption about an assumption, and the sensitivity experiment must say so.
 *
 * Literal values only. No arithmetic: derived quantities such as the sphere
 * radius are written out longhand with the derivation in the note.
 */

/** Provenance classes, PARAMETERS.md "How to read this". */
export type ParamClass = 'DOC' | 'CFG' | 'SOLVE' | 'ASSUME' | 'MEAS';

export interface ParamSpec {
  /** Symbol as written in PARAMETERS.md. */
  symbol: string;
  /** Human-readable name. */
  name: string;
  /** Section of PARAMETERS.md this comes from. */
  section: string;
  klass: ParamClass;
  /** Nominal value. Units per `unit`. */
  nominal: number;
  unit: string;
  /** Lower and upper end of the plausible range, for sweeps. */
  min: number;
  max: number;
  /** Whether PARAMETERS.md states the range, or we inferred it. */
  rangeSource: 'stated' | 'inferred';
  /** Whether this parameter feeds geometric metrics, photometric metrics, or both. */
  affects: 'geometry' | 'photometry' | 'both';
  note: string;
}

/**
 * Parameters that the sensitivity experiment sweeps. Keyed by a stable id so
 * results can be joined across runs.
 */
export const PARAMETER_TABLE: Record<string, ParamSpec> = {
  // ---- §1 Sphere geometry -------------------------------------------------
  D_sphere: {
    symbol: 'D_sphere',
    name: 'Sphere diameter',
    section: '§1',
    klass: 'DOC',
    nominal: 1.7272,
    unit: 'm',
    min: 1.7272,
    max: 1.7272,
    rangeSource: 'stated',
    affects: 'geometry',
    note: '68 in. Standard carbon-fibre sphere. Other sizes exist; keep configurable.',
  },
  R: {
    symbol: 'R',
    name: 'Sphere radius',
    section: '§1',
    klass: 'DOC',
    nominal: 0.8636,
    unit: 'm',
    min: 0.8636,
    max: 0.8636,
    rangeSource: 'stated',
    affects: 'geometry',
    note: 'Derived as half of D_sphere; written longhand because this package holds no arithmetic.',
  },
  h_bottom: {
    symbol: 'h_bottom',
    name: 'Floor to sphere bottom',
    section: '§1',
    klass: 'DOC',
    nominal: 1.3208,
    unit: 'm',
    min: 1.3208,
    max: 1.3208,
    rangeSource: 'stated',
    affects: 'geometry',
    note: '52 in.',
  },
  h_center: {
    symbol: 'h_center',
    name: 'Floor to sphere centre',
    section: '§1',
    klass: 'SOLVE',
    nominal: 2.1844,
    unit: 'm',
    min: 2.1590,
    max: 2.2098,
    rangeSource: 'inferred',
    affects: 'geometry',
    note: '86 in. Range is the documented plus-or-minus one inch trial-and-error correction the alignment tips describe. Solved, not measured.',
  },
  rho_R: {
    symbol: 'ρ_R',
    name: 'Diffuse reflectance, red',
    section: '§1',
    klass: 'ASSUME',
    nominal: 0.9,
    unit: '',
    min: 0.8,
    max: 0.95,
    rangeSource: 'inferred',
    affects: 'photometry',
    note: 'Matte white paint. PARAMETERS.md gives no range; §10 calls it narrower than the other three risks but says it scales every photometric result.',
  },
  rho_G: {
    symbol: 'ρ_G',
    name: 'Diffuse reflectance, green',
    section: '§1',
    klass: 'ASSUME',
    nominal: 0.9,
    unit: '',
    min: 0.8,
    max: 0.95,
    rangeSource: 'inferred',
    affects: 'photometry',
    note: 'As rho_R.',
  },
  rho_B: {
    symbol: 'ρ_B',
    name: 'Diffuse reflectance, blue',
    section: '§1',
    klass: 'ASSUME',
    nominal: 0.88,
    unit: '',
    min: 0.78,
    max: 0.95,
    rangeSource: 'inferred',
    affects: 'photometry',
    note: 'Slight blue falloff assumed; white paints commonly are not spectrally flat. Unpublished.',
  },
  rho_spec: {
    symbol: 'ρ_spec',
    name: 'Specular lobe weight',
    section: '§1',
    klass: 'ASSUME',
    nominal: 0.03,
    unit: '',
    min: 0.0,
    max: 0.08,
    rangeSource: 'stated',
    affects: 'photometry',
    note: 'PARAMETERS.md explicitly says to set it to 0 to test sensitivity, which fixes the low end.',
  },
  alpha_spec: {
    symbol: 'α_spec',
    name: 'Specular roughness (GGX)',
    section: '§1',
    klass: 'ASSUME',
    nominal: 0.4,
    unit: '',
    min: 0.2,
    max: 0.7,
    rangeSource: 'inferred',
    affects: 'photometry',
    note: 'Broad, dim lobe. PARAMETERS.md calls the nominal a pure guess and gives no range.',
  },
  theta_rot: {
    symbol: 'θ_rot',
    name: 'Sphere rotation vs prime meridian',
    section: '§1',
    klass: 'CFG',
    nominal: 0.0,
    unit: 'deg',
    min: -180.0,
    max: 180.0,
    rangeSource: 'inferred',
    affects: 'geometry',
    note: 'Sites rotate the sphere mechanically. Known per install.',
  },
  occl_top: {
    symbol: 'occl_top',
    name: 'Suspension hardware occlusion',
    section: '§1',
    klass: 'ASSUME',
    nominal: 6.0,
    unit: 'deg',
    min: 0.0,
    max: 12.0,
    rangeSource: 'inferred',
    affects: 'both',
    note: 'North polar cap obstructed by the mount. Explains why SOS masks only the bottom.',
  },

  // ---- §2 Projector placement --------------------------------------------
  d_proj: {
    symbol: 'd_proj',
    name: 'Sphere centre to lens distance',
    section: '§2',
    klass: 'SOLVE',
    nominal: 5.18,
    unit: 'm',
    min: 5.0,
    max: 6.5,
    rangeSource: 'stated',
    affects: 'geometry',
    note: 'CONFLICTED. Alignment manual says about 17 ft (5.18 m); floor plan implies 5.50-6.14 m. Wide prior 5.0-6.5 m, settle with a tape measure.',
  },
  h_proj: {
    symbol: 'h_proj',
    name: 'Projector height above floor',
    section: '§2',
    klass: 'SOLVE',
    nominal: 2.1844,
    unit: 'm',
    min: 1.8,
    max: 3.0,
    rangeSource: 'inferred',
    affects: 'geometry',
    note: 'Documentation says projectors are generally at the same 7 ft 2 in as the equator.',
  },
  phi_jitter: {
    symbol: 'φ_i',
    name: 'Azimuth mount tolerance',
    section: '§2',
    klass: 'SOLVE',
    nominal: 0.0,
    unit: 'deg',
    min: -2.0,
    max: 2.0,
    rangeSource: 'stated',
    affects: 'geometry',
    note: 'Real mounts hold plus or minus 1-2 degrees about the nominal 0/90/180/270.',
  },

  // ---- §3 Optics and transfer --------------------------------------------
  T_throw: {
    symbol: 'T',
    name: 'Throw ratio',
    section: '§3.1',
    klass: 'CFG',
    nominal: 3.0,
    unit: ':1',
    min: 2.5,
    max: 3.5,
    rangeSource: 'inferred',
    affects: 'geometry',
    note: 'Long-throw lens. See docs/AMENDMENTS.md A-01: which raster dimension the sphere diameter matches is not stated, and the two readings differ materially.',
  },
  gamma_R: {
    symbol: 'γ_R',
    name: 'Transfer exponent, red',
    section: '§3.2',
    klass: 'ASSUME',
    nominal: 2.2,
    unit: '',
    min: 1.9,
    max: 2.5,
    rangeSource: 'stated',
    affects: 'photometry',
    note: 'Real projectors diverge 0.1-0.3 between channels. Twelve values across the rig.',
  },
  gamma_G: {
    symbol: 'γ_G',
    name: 'Transfer exponent, green',
    section: '§3.2',
    klass: 'ASSUME',
    nominal: 2.2,
    unit: '',
    min: 1.9,
    max: 2.5,
    rangeSource: 'stated',
    affects: 'photometry',
    note: 'As gamma_R.',
  },
  gamma_B: {
    symbol: 'γ_B',
    name: 'Transfer exponent, blue',
    section: '§3.2',
    klass: 'ASSUME',
    nominal: 2.2,
    unit: '',
    min: 1.9,
    max: 2.5,
    rangeSource: 'stated',
    affects: 'photometry',
    note: 'As gamma_R. PARAMETERS.md §10 ranks per-channel gamma divergence the single highest photometric risk.',
  },
  L_black_R: {
    symbol: 'L_black_R',
    name: 'Black floor, red',
    section: '§3.2',
    klass: 'ASSUME',
    nominal: 0.00125,
    unit: 'fraction',
    min: 0.0005,
    max: 0.003333,
    rangeSource: 'stated',
    affects: 'photometry',
    note: '1/800 nominal, plausible range 1/2000 to 1/300. Spans roughly 6x.',
  },
  L_black_G: {
    symbol: 'L_black_G',
    name: 'Black floor, green',
    section: '§3.2',
    klass: 'ASSUME',
    nominal: 0.00125,
    unit: 'fraction',
    min: 0.0005,
    max: 0.003333,
    rangeSource: 'stated',
    affects: 'photometry',
    note: 'As L_black_R.',
  },
  L_black_B: {
    symbol: 'L_black_B',
    name: 'Black floor, blue',
    section: '§3.2',
    klass: 'ASSUME',
    nominal: 0.00125,
    unit: 'fraction',
    min: 0.0005,
    max: 0.003333,
    rangeSource: 'stated',
    affects: 'photometry',
    note: 'DLP and LCD leak differently per channel; the uplift in overlaps is tinted, usually blue-gray.',
  },
  g_R: {
    symbol: 'g_R',
    name: 'Channel gain, red',
    section: '§3.2',
    klass: 'ASSUME',
    nominal: 1.0,
    unit: '',
    min: 0.85,
    max: 1.15,
    rangeSource: 'inferred',
    affects: 'photometry',
    note: 'Lamp aging diverges between projectors. Four lamps at different hour counts give four different white points.',
  },
  g_G: {
    symbol: 'g_G',
    name: 'Channel gain, green',
    section: '§3.2',
    klass: 'ASSUME',
    nominal: 1.0,
    unit: '',
    min: 0.85,
    max: 1.15,
    rangeSource: 'inferred',
    affects: 'photometry',
    note: 'As g_R.',
  },
  g_B: {
    symbol: 'g_B',
    name: 'Channel gain, blue',
    section: '§3.2',
    klass: 'ASSUME',
    nominal: 1.0,
    unit: '',
    min: 0.85,
    max: 1.15,
    rangeSource: 'inferred',
    affects: 'photometry',
    note: 'As g_R.',
  },
  wp: {
    symbol: 'wp_i',
    name: 'White point',
    section: '§3.2',
    klass: 'ASSUME',
    nominal: 6500.0,
    unit: 'K',
    min: 5500.0,
    max: 7500.0,
    rangeSource: 'inferred',
    affects: 'photometry',
    note: 'Derived from gain; tracked separately for reporting.',
  },

  // ---- §4 Blending and masking -------------------------------------------
  w_width: {
    symbol: 'w_width',
    name: 'Blend region angular width',
    section: '§4.5',
    klass: 'ASSUME',
    nominal: 20.0,
    unit: 'deg',
    min: 5.0,
    max: 40.0,
    rangeSource: 'inferred',
    affects: 'both',
    note: 'Derived from seam geometry in PARAMETERS.md; shape and width both unpublished. Experiment 2 sweeps this against registration error.',
  },
  gamma_blend: {
    symbol: 'γ_blend',
    name: 'Blend ramp exponent',
    section: '§4.5',
    klass: 'DOC',
    nominal: 0.8,
    unit: '',
    min: 0.5,
    max: 1.5,
    rangeSource: 'inferred',
    affects: 'photometry',
    note: 'From the SOS config. One global scalar for four projectors and three channels; cannot correct a chromatic seam.',
  },
  mask_lo: {
    symbol: 'mask_lo',
    name: 'Polar mask onset',
    section: '§4.5',
    klass: 'DOC',
    nominal: 60.0,
    unit: 'deg lat',
    min: 50.0,
    max: 70.0,
    rangeSource: 'inferred',
    affects: 'both',
    note: 'From `set bottommask 60,70`. Latitude units INFERRED, not published. Matches the seam-direction usable limit of about 59 deg.',
  },
  mask_hi: {
    symbol: 'mask_hi',
    name: 'Polar mask full',
    section: '§4.5',
    klass: 'DOC',
    nominal: 70.0,
    unit: 'deg lat',
    min: 60.0,
    max: 80.0,
    rangeSource: 'inferred',
    affects: 'both',
    note: 'As mask_lo. Ten-degree feather to full mask.',
  },

  // ---- §5 Room environment ------------------------------------------------
  E_amb: {
    symbol: 'E_amb',
    name: 'Ambient luminance on sphere',
    section: '§5',
    klass: 'ASSUME',
    nominal: 0.04,
    unit: 'relative',
    min: 0.01,
    max: 0.15,
    rangeSource: 'stated',
    affects: 'photometry',
    note: 'NOAA note that ambient and direct light throw off their CV, and that their own lighting control is unusually good, implying typical sites are worse.',
  },
  E_amb_chroma: {
    symbol: 'E_amb_chroma',
    name: 'Ambient colour temperature',
    section: '§5',
    klass: 'ASSUME',
    nominal: 4000.0,
    unit: 'K',
    min: 2700.0,
    max: 6500.0,
    rangeSource: 'inferred',
    affects: 'photometry',
    note: 'Exhibit lighting is rarely daylight-balanced. Tints the whole sphere and shifts every deltaE.',
  },
  rho_room: {
    symbol: 'ρ_room',
    name: 'Wall and floor albedo',
    section: '§5',
    klass: 'ASSUME',
    nominal: 0.3,
    unit: '',
    min: 0.15,
    max: 0.6,
    rangeSource: 'inferred',
    affects: 'photometry',
    note: 'Only matters via inter-reflection, which §9 lists as not modelled in v1.',
  },

  // ---- §6 Viewer ----------------------------------------------------------
  h_eye_adult: {
    symbol: 'h_eye',
    name: 'Eye height, adult',
    section: '§6',
    klass: 'ASSUME',
    nominal: 1.6,
    unit: 'm',
    min: 1.5,
    max: 1.85,
    rangeSource: 'inferred',
    affects: 'geometry',
    note: 'The equator sits at 2.18 m, so everyone looks up. PARAMETERS.md says run both adult and child.',
  },
  h_eye_child: {
    symbol: 'h_eye',
    name: 'Eye height, child',
    section: '§6',
    klass: 'ASSUME',
    nominal: 1.15,
    unit: 'm',
    min: 0.9,
    max: 1.4,
    rangeSource: 'inferred',
    affects: 'geometry',
    note: 'Children look up steeply and are a large share of the SOS audience.',
  },
  d_view: {
    symbol: 'd_view',
    name: 'Viewing distance from sphere centre',
    section: '§6',
    klass: 'CFG',
    nominal: 2.5,
    unit: 'm',
    min: 2.0,
    max: 3.5,
    rangeSource: 'stated',
    affects: 'geometry',
    note: 'Bounded below by the guard rail.',
  },
  fov_eye: {
    symbol: 'fov_eye',
    name: 'Viewer camera field of view',
    section: '§6',
    klass: 'ASSUME',
    nominal: 50.0,
    unit: 'deg',
    min: 35.0,
    max: 70.0,
    rangeSource: 'inferred',
    affects: 'geometry',
    note: 'Framing choice. PARAMETERS.md is explicit that metric values must not depend on it — the bench asserts this.',
  },
};

/** The ASSUME-class parameters the photometric sensitivity experiment must sweep. */
export const ASSUME_PHOTOMETRIC_IDS: string[] = [
  'rho_R',
  'rho_G',
  'rho_B',
  'rho_spec',
  'alpha_spec',
  'gamma_R',
  'gamma_G',
  'gamma_B',
  'L_black_R',
  'L_black_G',
  'L_black_B',
  'g_R',
  'g_G',
  'g_B',
  'wp',
  'w_width',
  'E_amb',
  'E_amb_chroma',
  'mask_lo',
  'mask_hi',
];

/** Acceptance gates, PARAMETERS.md §7. */
export interface MetricGate {
  id: string;
  metric: string;
  /** Inclusive upper bound the metric must not exceed. */
  max: number;
  unit: string;
  klass: ParamClass | 'DERIVED';
  phase: 'geometry' | 'photometry';
  basis: string;
}

export const GATES: MetricGate[] = [
  {
    id: 'grid_displacement',
    metric: 'Grid-line displacement across a blend region',
    max: 1.0,
    unit: 'mm on sphere surface',
    klass: 'ASSUME',
    phase: 'geometry',
    basis: 'About 1 arcmin at 2.5 m.',
  },
  {
    id: 'pose_position',
    metric: 'Pose recovery position error',
    max: 0.002,
    unit: 'm',
    klass: 'DERIVED',
    phase: 'geometry',
    basis: 'Chosen so geometric error is dominated by other terms.',
  },
  {
    id: 'pose_rotation',
    metric: 'Pose recovery rotation error',
    max: 0.05,
    unit: 'deg',
    klass: 'DERIVED',
    phase: 'geometry',
    basis: 'Chosen so geometric error is dominated by other terms.',
  },
  {
    id: 'off_sphere_flux',
    metric: 'Off-sphere flux (Red Ball equivalent)',
    max: 0.52,
    unit: 'fraction',
    klass: 'ASSUME',
    phase: 'geometry',
    basis: 'Floor is about 51% from raster geometry. Catches gross misaim. See AMENDMENTS.md A-01.',
  },
  {
    id: 'unlit_in_mask',
    metric: 'Unlit fraction within the mask boundary',
    max: 0.0,
    unit: 'fraction',
    klass: 'DERIVED',
    phase: 'geometry',
    basis: 'Hard requirement. Computed inside mask_lo, not over the full sphere.',
  },
  {
    id: 'seam_luminance',
    metric: 'Seam luminance discontinuity',
    max: 0.02,
    unit: 'fraction of local mean',
    klass: 'ASSUME',
    phase: 'photometry',
    basis: 'Weber fraction for a step in a smooth field. PROVISIONAL.',
  },
  {
    id: 'seam_chroma',
    metric: 'Seam chromaticity discontinuity',
    max: 1.0,
    unit: 'dE2000',
    klass: 'ASSUME',
    phase: 'photometry',
    basis: 'Classic just-noticeable difference. The eye is more sensitive to chromatic edges. PROVISIONAL.',
  },
  {
    id: 'black_uplift',
    metric: 'Black uplift ratio, overlap over single',
    max: 1.2,
    unit: 'ratio',
    klass: 'ASSUME',
    phase: 'photometry',
    basis: 'Below where an overlap band reads as a visible rectangle in dark content. PROVISIONAL.',
  },
  {
    id: 'black_uplift_chroma',
    metric: 'Black uplift chromaticity shift',
    max: 2.0,
    unit: 'dE2000',
    klass: 'ASSUME',
    phase: 'photometry',
    basis: 'Looser than the highlight gate; chromatic discrimination is poorer in dark content. PROVISIONAL.',
  },
];
