/**
 * Assemble everything publishable into `site/`. `node tools/build-site.ts`
 *
 * Three pages, and they are for three different readers:
 *
 *   - **`/app/`** — the interactive simulator. For somebody who wants to
 *     understand what a projected sphere does and what calibrating one buys.
 *   - **`/harness/`** — the developer harness. Five viewports, a slider per
 *     constant carrying its provenance class, and the GPU↔CPU parity number.
 *   - **`/progress/`** — the measurement record, if one has been generated.
 *
 * The landing page is written here rather than kept as a file, because it is
 * nothing but links and a paragraph and a separate file would drift out of date
 * with what the directory actually contains: this one is generated FROM what
 * was found.
 *
 * ## What is deliberately not published
 *
 * `validation/`. It holds photographs of real installations beside our render,
 * and PARAMETERS.md's brief is explicit that provenance is unknown until the
 * owner says otherwise — NOAA imagery is generally public domain but
 * site-submitted photographs may not be. A page that is not published cannot
 * republish somebody's photograph by accident.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SITE = path.join(ROOT, 'site');

interface Page {
  slug: string;
  title: string;
  blurb: string;
  /** Directories copied verbatim into `site/<slug>/`. */
  sources: { from: string; to: string }[];
  /** Present only if this file exists; otherwise the page is skipped. */
  requires: string;
}

const PAGES: Page[] = [
  {
    slug: 'app',
    title: 'Installation simulator',
    blurb:
      'A projected sphere you can walk around. Every number beside the picture is computed by the ' +
      'project’s forward model in a worker, and the picture and the model are compared against each ' +
      'other continuously. Press Recalibrate and the inverse model runs a full structured-light ' +
      'solve in your browser — a real capture, a real bundle adjustment, about five seconds.',
    sources: [
      { from: 'packages/web/index.html', to: 'index.html' },
      { from: 'packages/web/dist', to: 'dist' },
      { from: 'packages/web/assets', to: 'assets' },
    ],
    requires: 'packages/web/dist/web/web/main.js',
  },
  {
    slug: 'harness',
    title: 'Developer harness',
    blurb:
      'One WebGL2 context, five viewports: the room, and the four projector rasters as quadrants of ' +
      'the single framebuffer SOS actually drives. Every slider carries the provenance class of the ' +
      'constant it moves, and anything resting on an unmeasured one is marked PROVISIONAL.',
    sources: [
      { from: 'packages/harness/index.html', to: 'index.html' },
      { from: 'packages/harness/dist', to: 'dist' },
    ],
    requires: 'packages/harness/dist/harness/web/main.js',
  },
  {
    slug: 'progress',
    title: 'Measurement record',
    blurb:
      'Where the numbers stand against PARAMETERS.md §7, what moved between rounds, and the three ' +
      'experiments. Generated by the bench; absent when the bench has not been run.',
    sources: [{ from: 'progress', to: '.' }],
    requires: 'progress/index.html',
  },
];

function copyRecursive(from: string, to: string): number {
  const stat = fs.statSync(from);
  if (!stat.isDirectory()) {
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(from, to);
    return 1;
  }
  fs.mkdirSync(to, { recursive: true });
  let n = 0;
  for (const entry of fs.readdirSync(from)) {
    n += copyRecursive(path.join(from, entry), path.join(to, entry));
  }
  return n;
}

function landingPage(published: Page[]): string {
  const cards = published
    .map(
      (p) => `    <a class="card" href="./${p.slug}/">
      <h2>${p.title}</h2>
      <p>${p.blurb}</p>
    </a>`,
    )
    .join('\n');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>sphere-sim</title>
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Ccircle cx='16' cy='16' r='11' fill='%232b5fd9'/%3E%3Cpath d='M5 16h22M16 5v22' stroke='%23fff' stroke-width='1.4' opacity='.7'/%3E%3C/svg%3E"/>
<style>
:root { color-scheme: light dark;
  --bg:#fbfbfa; --panel:#fff; --fg:#1a1a1a; --muted:#5c6470; --line:#d9dde3; --accent:#2b5fd9; }
@media (prefers-color-scheme: dark) { :root {
  --bg:#14161a; --panel:#1b1e24; --fg:#e8eaed; --muted:#9aa3af; --line:#333944; --accent:#7aa2ff; } }
* { box-sizing: border-box; }
body { margin:0; background:var(--bg); color:var(--fg); padding:48px 20px 64px;
  font:16px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; }
main { max-width: 760px; margin: 0 auto; }
h1 { font-size: 30px; letter-spacing:-0.02em; margin:0 0 6px; }
.lede { color: var(--muted); margin: 0 0 8px; }
.why { border-left: 3px solid var(--accent); padding: 2px 0 2px 14px; margin: 26px 0 30px;
  color: var(--muted); font-size: 15px; }
.why strong { color: var(--fg); }
.cards { display: grid; gap: 14px; }
.card { display:block; text-decoration:none; color:inherit; background:var(--panel);
  border:1px solid var(--line); border-radius:9px; padding:16px 18px; transition: border-color .15s; }
.card:hover { border-color: var(--accent); }
.card h2 { margin:0 0 6px; font-size:18px; color:var(--accent); }
.card p { margin:0; color:var(--muted); font-size:14.5px; }
footer { margin-top: 36px; padding-top: 18px; border-top:1px solid var(--line);
  color:var(--muted); font-size:13px; }
footer a { color: var(--accent); }
code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 0.9em; }
</style>
</head>
<body>
<main>
  <h1>sphere-sim</h1>
  <p class="lede">A physically-based simulator of a projected spherical display, and an alignment
  solver that calibrates one from camera images.</p>

  <div class="why">
    The two are <strong>deliberately independent</strong>. They share no geometry code, no projection
    math and no distortion model — only a JSON document and the prose describing what its numbers
    mean. If they shared implementation the solver would be inverting the simulator’s own arithmetic,
    every recovery score would be circular, and the project would be worthless. A lint rule fails the
    build on any import across that line.
  </div>

  <div class="cards">
${cards}
  </div>

  <footer>
    Source, the parameter specification it is built against, and the amendments raised while
    implementing it: <a href="https://github.com/zyra-project/sphere-sim">github.com/zyra-project/sphere-sim</a>.
    <br/><br/>
    Science On a Sphere<sup>®</sup> is a registered trademark of NOAA. This is an independent
    simulator and is not a NOAA product. The simulator opens at NOAA Boulder’s published
    <code>sos_stream_control.config</code>, which disagrees with this project’s specification on
    three constants — see amendment A-36.
  </footer>
</main>
</body>
</html>
`;
}

function main(): void {
  fs.rmSync(SITE, { recursive: true, force: true });
  fs.mkdirSync(SITE, { recursive: true });

  const published: Page[] = [];
  for (const page of PAGES) {
    if (!fs.existsSync(path.join(ROOT, page.requires))) {
      console.log(`  skip  ${page.slug}  (${page.requires} is not built)`);
      continue;
    }
    let files = 0;
    for (const src of page.sources) {
      const from = path.join(ROOT, src.from);
      if (!fs.existsSync(from)) continue;
      files += copyRecursive(from, path.join(SITE, page.slug, src.to));
    }
    console.log(`  ok    ${page.slug}  ${files} file(s)`);
    published.push(page);
  }

  if (published.length === 0) {
    console.error('\nnothing to publish. Run `npm run build:app` and `npm run build:web` first.\n');
    process.exitCode = 1;
    return;
  }

  fs.writeFileSync(path.join(SITE, 'index.html'), landingPage(published));
  // GitHub Pages runs Jekyll by default, which silently drops any path with a
  // leading underscore. Nothing here has one today; the file costs nothing and
  // the failure mode it prevents is a missing asset with no error anywhere.
  fs.writeFileSync(path.join(SITE, '.nojekyll'), '');
  console.log(`\nwrote site/ — ${published.length} page(s) plus a landing page\n`);
}

main();
